[workspace]
members = [
    "hello_world",
    "types",
    "self_types",
    "variable_bind",
    "variable_cast",
    "control",
    "function",
    "modd",
    "crates",
    "attribute",
    "generic",
    "scope_rules",
    "trait_test",
    "macro_test",
]